### ISSUE TITLE
Using minFQ with ip (other than 127.0.0.1) seem to have port issues (failed to connect all addresses)?

### ISSUE THREAD

**Issue by rubru2019** [LooseLab/minotour-docker#3]
When I try to run minFQ / minotour on Docker, I get RPC error. 
minFQ -k 2645d7e2ebalablabla -ip 145.xxx.xxx.xxx -hn localhost -p 8100 -nf
->
<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1653160488.112296657","description":"Failed to pick subchannel",

Debugging -> tail -f -n 100 /var/lib/minotour/logs/celery.log
16624:[2022-05-20 23:02:08,011: ERROR/ForkPoolWorker-1] artic.utils.update_pangolin[06bde82d-5482-4173-87ed-5103c3a353c6]: b'pangolin updated to v4.0.6\npangolearn updated to 2022-04-22\nconstellations updated to v0.1.10\nscorpio updated to v0.3.17\npango-designation updated to v1.9\n'

**Comment by Adoni5** [comment]
Hi @rubru2019, 

Apologies, I missed this yesterday! Do you know what version of minKNOW core you were trying to connect to? You can find this in the minKNOW GUI under host settings. 

Could you also check the minFQ version and post it here?

```bash
minFQ --version
 ```

**Comment by Adoni5** [comment]
Looking at this [stackoverflow post](https://stackoverflow.com/questions/69444526/python-grpc-failed-to-pick-subchannel) - and the [GRPC status codes](https://grpc.github.io/grpc/core/md_doc_statuscodes.html) it looks like the server is unavailable. Do you know what port you are connecting on? Could the remote server be fire walled?

**Comment by rubru2019** [comment]
> Hi @rubru2019,
> 
> Apologies, I missed this yesterday! Do you know what version of minKNOW core you were trying to connect to? You can find this in the minKNOW GUI under host settings.
> 
> Could you also check the minFQ version and post it here?
> 
> ```shell
> minFQ --version
> ```

minKNOW core = 5.0.0
minKNOW = 22.03.2
minFQ = 1.4.7

**Comment by rubru2019** [comment]
> Looking at this [stackoverflow post](https://stackoverflow.com/questions/69444526/python-grpc-failed-to-pick-subchannel) - and the [GRPC status codes](https://grpc.github.io/grpc/core/md_doc_statuscodes.html) it looks like the server is unavailable. Do you know what port you are connecting on? Could the remote server be fire walled?

port = 5902
Remote server is on same internal network - not likely firewalled - I need to check. Port 5902 is open, because I am able to use Python API on this port 

Verify API is installed correctly (from a checkout of this repository):
> python ./python/minknow_api/examples/list_sequencing_positions.py --host localhost --port 9502

(I do get badmeta key error - when "User could call {pos.connect()} here to connect to the running MinKNOW instance"). Jevansio suggests: "_in your minknow folder, edit the app_conf file and set application.rpc.guest_access_default to "enabled_" 

I haven't check this because I am currently unable, I have no rights to ssh to the MinKNOW server...
