### ISSUE TITLE
Problems with GUI

### ISSUE THREAD

**Issue by lhoffmann97** [LooseLab/minotour-docker#6]
I have a problem with the graphical user interface. I used the Docker solution to install minoTour. I´ve also created an account - a normal user as well as an admin - but it is just possible for me to login in minoTour from the computer where I´ve installed the normal user and the admin. I cannot login in minoTour from another computer although the installation of the other computer was succesful.

**Comment by Adoni5** [comment]
Closed as I've answered this here https://github.com/LooseLab/minotourapp/issues/345
